import { Router } from "express";
import { createusuario, dataCorreos, login, setDatosUsuario, updateusuario,getusuario} from "../controllers/task.controllers.js"
import { getCliente, updateCliente, getClientsbyDNI, getAllClientes, getAlldistritos,getAllregion,getAlleducativo,getAllestado,getAllmotivo, deleteCliente, deleteClientes, createcliente, getAllusuario, getDistrito, getRegion, getEstado, getEducativo, getMotivo, deleteAllClientes, getClientesbyNivelEducativo, getClientesbyMotivo, getClientesbyEstadoCivil, getClientesbyDistrito, getClientesbyRegion, getClientesbyMotivoDistrito, getClientesbyNivelEducativoDistrito, getClientesbyEstadoCivilDistrito, getClientesbyNivelEducativoRegion, getClientesbyMotivoRegion, getClientesbyEstadoCivilRegion, getDistritosbyRegion, getAllClientesbyRegion, getAllClientesbyDistrito, getClientsbyDNIigual, getAllDistritosbyRegion} from "../controllers/cliente.controller.js"
const router=Router();

router.post('/registrousuario',createusuario)
router.put('/registrousuario1',login)
router.get('/distrito',getAlldistritos)
router.get('/distrito/:id',getDistrito)
router.get('/region',getAllregion)
router.get('/region/:id',getRegion)
router.get('/motivo',getAllmotivo)
router.get('/motivo/:id',getMotivo)
router.get('/estado',getAllestado)
router.get('/estado/:id',getEstado)
router.get('/educativo',getAlleducativo)
router.get('/educativo/:id',getEducativo)
router.get('/usuarios/:id',getusuario)
router.get('/usuario',getAllusuario)
router.put('/usuario',updateusuario)
router.post('/usuario2',setDatosUsuario)
router.post('/correo', dataCorreos)
router.post('/cliente',createcliente)
router.get('/clientes/:userId',getAllClientes)
router.get('/clients/:id/:userId',getClientsbyDNI)
router.get('/clientsf/:id/:userId',getClientsbyDNIigual)
router.get('/clientesporeducativo/:id/:userId',getClientesbyNivelEducativo)
router.get('/clientesporeducativodistrito/:id/:distrito/:userId',getClientesbyNivelEducativoDistrito)
router.get('/clientesporeducativoregion/:id/:region/:userId',getClientesbyNivelEducativoRegion)
router.get('/clientespormotivo/:id/:userId',getClientesbyMotivo)
router.get('/clientespormotivodistrito/:id/:distrito/:userId',getClientesbyMotivoDistrito)
router.get('/clientespormotivoregion/:id/:region/:userId',getClientesbyMotivoRegion)
router.get('/clientesporestadocivil/:id/:userId',getClientesbyEstadoCivil)
router.get('/clientesporestadocivildistrito/:id/:distrito/:userId',getClientesbyEstadoCivilDistrito)
router.get('/clientesporestadocivilregion/:id/:region/:userId',getClientesbyEstadoCivilRegion)
router.get('/clientespordistrito/:id/:userId',getClientesbyDistrito)
router.get('/allclientespordistrito/:id/:userId',getAllClientesbyDistrito)
router.get('/clientesporregion/:id/:userId',getClientesbyRegion)
router.get('/allclientesporregion/:id/:userId',getAllClientesbyRegion)
router.get('/distritosporregion/:id/:userId' ,getDistritosbyRegion)
router.get('/alldistritosporregion/:id' ,getAllDistritosbyRegion)
router.get('/cliente/:id',getCliente)
router.put('/cliente/:id',updateCliente)
router.delete('/cliente/:id',deleteCliente)
router.delete('/clientes/:userId',deleteClientes)
router.delete('/clientes',deleteAllClientes)
export default router;